Update validator.yml

diff --git a/.github/workflows/validator.yml b/.github/workflows/validator.yml
--- a/.github/workflows/validator.yml
+++ b/.github/workflows/validator.yml
@@ -87,30 +87,26 @@ jobs:
                 if ! jq -e '.owner | has("email")' $content > /dev/null; then
                   echo "ERROR_REQ_OWNER_EMAIL= - owner/email" >>  "$GITHUB_OUTPUT"
                 fi
-                if jq -e 'has("use_github_avatar")' $content > /dev/null; then
-                  isPic=$(cat $content | jq -r '.use_github_avatar')
-                  echo "JSON_USE_PIC= $isPic" >>  "$GITHUB_OUTPUT";
+                if ! jq -e 'has("use_github_avatar")' $content > /dev/null; then
+                  echo "ERROR_REQ_PIC= - use_github_avatar" >>  "$GITHUB_OUTPUT";
+                else
+                  if [ cat $content | jq -r '.use_github_avatar' ]; then
+                    isPic=$(cat $content | jq -r '.use_github_avatar')
+                    echo "JSON_USE_PIC=$isPic" >>  "$GITHUB_OUTPUT";
+                  fi
                 fi
 
                 # check for profanity in owner.name
                 if jq -r '.owner.name' $content | grep -Fiq -f <(curl -s "https://raw.githubusercontent.com/{owner}/profanity-filter/refs/heads/main/src/ProfanityFilter.Services/Data/GoogleBannedWords.txt"); then
-
+                  echo "PROFANITY_1= - Possible Profanity in Name" >>  "$GITHUB_OUTPUT";
+                  echo "Profanity detected in Name!"
+                  fi
+                  
+                  # check for profanity in description
+                  if jq -r '.description' $content | grep -Fiq -f <(curl -s "https://raw.githubusercontent.com/{owner}/profanity-filter/refs/heads/main/src/ProfanityFilter.Services/Data/GoogleBannedWords.txt"); then
+                  echo "PROFANITY_2= - Possible Profanity in Description" >>  "$GITHUB_OUTPUT";
                   echo "Profanity detected!"
-
-                else
-
-                  echo "No profanity detected."
-
-                fi
-
-                # check for profanity in description
-                if jq -r '.description' $content | grep -Fiq -f <(curl -s "https://raw.githubusercontent.com/{owner}/profanity-filter/refs/heads/main/src/ProfanityFilter.Services/Data/GoogleBannedWords.txt"); then
-
-                  echo "Profanity detected!"
-
-                else
-
-                  echo "No profanity detected."
+                  echo "No profanity detected in Description!"
 
                 fi
               fi
@@ -139,11 +135,58 @@ jobs:
             ${{ steps.checker.outputs.ERROR_FILE }}
             ${{ steps.checker.outputs.ERROR_CONTENT }}
             ${{steps.checker.outputs.ERROR_DELETE}}
-            For more info, please visit our [documentaion](https://First-Accord.js.org/docs)
+            For more info, please visit our [documentaion](https://first-accord.js.org/docs/#/json-structure)
 
+      - name: Closing JSON result 1
+        if: ${{steps.checker.outputs.ERROR_COUNT}} || ${{ steps.checker.outputs.ERROR_FILE }} || ${{ steps.checker.outputs.ERROR_CONTENT }} || ${{steps.checker.outputs.ERROR_DELETE}}
+        run: |
+              gh pr close ${{ github.event.pull_request.number }} --comment "Auto-closing pull request, you are welcome to reopen or create a new pull request."
+              gh pr edit ${{ github.event.pull_request.number }} --add-label "invalid"
+              exit 1
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      
       - name: Checking JSON result 2
-        if: ${{steps.checker.outputs.ERROR_COUNT}} || ${{ steps.checker.outputs.ERROR_FILE }} || ${{ steps.checker.outputs.ERROR_CONTENT }}
-        run: gh pr close ${{ github.event.pull_request.number }} --comment "Auto-closing pull request, you are welcome to reopen or create a new pull request."
+        if: ${{steps.checker.outputs.ERROR_REQ_OWNER}} || ${{steps.checker.outputs.ERROR_REQ_OWNER_NAME}} || ${{steps.checker.outputs.ERROR_REQ_OWNER_EMAIL}} || ${{steps.checker.outputs.ERROR_REQ_PIC}}
+        uses: thollander/actions-comment-pull-request@v3
+        with:
+          message: |
+            Required Items can't be found:
+              ${{steps.checker.outputs.ERROR_REQ_OWNER}}
+              ${{steps.checker.outputs.ERROR_REQ_OWNER_NAME}}
+              ${{steps.checker.outputs.ERROR_REQ_OWNER_EMAIL}}
+              ${{steps.checker.outputs.ERROR_REQ_PIC}}
+            
+            For more info about the `Required Items`, please [visit here](https://first-accord.js.org/docs/#/json-structure)
+
+      - name: closing JSON result 2
+        run: |
+              gh pr edit ${{ github.event.pull_request.number }} --add-label "invalid"
+              exit 1
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Checking JSON result 3
+        if: ${{steps.checker.outputs.PROFANITY_1}} || ${{steps.checker.outputs.PROFANITY_1}} || ${{steps.checker.outputs.JSON_USE_PIC}}
+        uses: thollander/actions-comment-pull-request@v3
+        with:
+          message: |
+            Requesting @STICKnoLOGIC, kindly review the possible problem:
+              ${{steps.checker.outputs.PROFANITY_1}}
+              ${{steps.checker.outputs.PROFANITY_2}}
+              ${{steps.checker.outputs.JSON_USE_PIC}}
+            Thank You! 😁😁
+      
+      - name: closing JSON 3 result
+        run: |
+              labels="r: Yhal"
+              if [ ${{steps.checker.outputs.PROFANITY_1}} || ${{steps.checker.outputs.PROFANITY_2}}]; then
+                labels+=",r: Yhal-avatar"
+              fi
+              if [ ${{steps.checker.outputs.JSON_USE_PIC}} ]; then
+                labels+=",possible Profanity"
+              fi
+              gh pr edit ${{ github.event.pull_request.number }} --add-label "invalid"
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
